### ISSUE TITLE
unsupported special dependency :qemu

### ISSUE THREAD

**Issue by unusualevent** [nanovms/homebrew-ops#11]
No idea why the formula is failing.
```
brew install nanovms/ops/ops          
Running `brew update --auto-update`...
Error: nanovms/ops/ops: Unsupported special dependency :qemu
```

Homebrew 4.2.2

Apple M1

Sonoma 14.2.1 (23C71)

**Comment by eyberg** [comment]
should be fixed w/ https://github.com/nanovms/homebrew-ops/commit/5eaef17f7fd1006199a102fe4a0de6bcf494c2e9
